name: ensemble
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.2
      - aiosignal==1.3.2
      - alembic==1.16.2
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - baikal==0.4.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - climage==0.2.2
      - cloudpickle==3.1.2
      - colorlog==6.9.0
      - comm==0.2.2
      - conch==0.1.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.6.0
      - decorator==5.2.1
      - dill==0.3.8
      - ecos==2.0.14
      - einops==0.8.1
      - einops-exts==0.0.4
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fairscale==0.4.13
      - fastcore==1.8.2
      - filelock==3.18.0
      - fonttools==4.58.0
      - frozenlist==1.6.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - geopandas==1.0.1
      - greenlet==3.2.3
      - h5py==3.13.0
      - hf-xet==1.1.2
      - huggingface-hub==0.32.3
      - idna==3.10
      - imgcat==0.6.0
      - inquirerpy==0.3.4
      - ipython==8.36.0
      - ipywidgets==8.1.7
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - jupyterlab-widgets==3.0.15
      - kdtree==0.16
      - kiwisolver==1.4.8
      - lovely-numpy==0.2.13
      - lovely-tensors==0.1.18
      - mako==1.3.10
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multidict==6.4.4
      - multiprocess==0.70.16
      - musk==1.0.0
      - networkx==3.4.2
      - numexpr==2.10.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.11.0.86
      - openslide-bin==4.0.0.8
      - openslide-python==1.4.2
      - optuna==4.4.0
      - osqp==0.6.7.post3
      - packaging==25.0
      - pandas==2.2.3
      - parso==0.8.4
      - patho-bench==0.0.1
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==11.2.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pygad==3.5.0
      - pygments==2.19.1
      - pyogrio==0.11.0
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - qdldl==0.1.7.post5
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scikit-survival==0.24.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - segmentation-models-pytorch==0.5.0
      - shapely==2.1.1
      - six==1.17.0
      - sqlalchemy==2.0.41
      - stack-data==0.6.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - timm==0.9.16
      - timm-ctp==0.5.4
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.52.3
      - trident==0.1.1
      - triton==3.3.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.14
      - xxhash==3.5.0
      - yarl==1.20.0
